// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RZAWeb.Data;

#nullable disable

namespace RZAWeb.Migrations
{
    [DbContext(typeof(RZAWebContext))]
    [Migration("20240325134212_InitialCreateHotelRooms")]
    partial class InitialCreateHotelRooms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RZAWeb.Models.BookHotelRooms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoubleRooms")
                        .HasColumnType("int");

                    b.Property<int?>("FamilyRooms")
                        .HasColumnType("int");

                    b.Property<int?>("SingleRooms")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BookHotelTickets");
                });

            modelBuilder.Entity("RZAWeb.Models.BookZooTickets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdultTickets")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChildTickets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BookZooTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
